stages:
  - plan
  - apply
  - ansible

variables:
  AWS_REGION: "sa-east-1"
  TF_STATE_BUCKET: "anderson0933-sa-east-1-terrafome-statefile"  # Substitua com o nome do seu bucket do S3 para armazenar o estado
  TF_STATE_KEY: "terraform.tfstate"
  TF_BACKEND_CONFIG: "-backend-config=region=${AWS_REGION} -backend-config=bucket=${TF_STATE_BUCKET} -backend-config=key=${TF_STATE_KEY}"

before_script:
  - apt-get update && apt-get install -y python3-pip
  - pip3 install boto3 ansible

# Job 1: Configuração do Terraform - Terraform Init e Plan
terraform_plan:
  stage: plan
  image: hashicorp/terraform:latest
  script:
    - terraform init $TF_BACKEND_CONFIG
    - terraform plan
  only:
    - main

# Job 2: Aplicação do Terraform - Criar ou Atualizar infraestrutura
terraform_apply:
  stage: apply
  image: hashicorp/terraform:latest
  script:
    - terraform apply -auto-approve $TF_BACKEND_CONFIG
  only:
    - main

# Job 3: Configuração do Ansible
ansible_setup:
  stage: ansible
  image: ansible/ansible:latest
  script:
    - ansible-playbook -i ansible/inventory.py ansible/setup.yml
  only:
    - main
